### ISSUE TITLE
null safety support

### ISSUE THREAD

**Issue by yarmel** [davigmacode/flutter_smart_select#89]
Error: Cannot run with sound null safety, because the following dependencies
    don't support null safety:

     - package:smart_select
     
--
Any thoughts about null safety version?

**Comment by simonkimi** [comment]
```yaml
smart_select:
  git:
    url: https://github.com/iktakahiro/flutter_smart_select.git
    ref: null-safety
```
